name: mankeli_analysis
description: A set of linting rules for static analysis. This package is used internally at Mankeli Software.
version: 1.1.2
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/mankeli_analysis
issue_tracker: https://github.com/Mankeli-Software/mankeli_analysis/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
